### ISSUE TITLE
mj绘画失败3.2.3版本

### ISSUE THREAD

**Issue by wshze** [yangjian102621/geekai#104]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

mj绘画失败，如图。大佬有空帮看看
![456](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/7c43c211-9fb9-4d38-8d73-d890878ce26e)
![789](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/2ec02b57-fdb2-4435-b814-c256a0e099b2)
![1234](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/a03e6dba-5b81-4f9f-a012-dc7da831b84f)

### 重现步骤 🕹

正常操作，改完config.toml配置重启 然后去页面上使用。3.2.3版本。是我配置有问题吗？

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
确保的你的魔法正常工作，这个是向 discord 发送请求失败。
