### ISSUE TITLE
使用DALLE3画图后图片无法显示

### ISSUE THREAD

**Issue by longtiequan** [yangjian102621/geekai#106]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

对话功能都是正常的，绘图功能只开启了DALLE3，对话完成后不显示图片
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/b074c9ec-13ab-4513-a648-4fb22ce7def0)
单看后台也没有什么报错
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/cc771d06-22ff-4433-ad5a-f7239eb4b8f0)

### 重现步骤 🕹

![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/0264afd9-d6d2-4cf5-9efe-07910e3e3c41)
![Screenshot 2024-01-10 142736](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/6926ae12-1b5e-4a2a-961c-f872a79407c3)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/d958832a-a0f9-474a-9448-922e6044c5aa)

**Comment by yangjian102621** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/fcf8d2ac-a150-48b4-bc4e-551946881876)
你在浏览器能否打开这张图？看起来是图片加载失败。

**Comment by longtiequan** [comment]
> ![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/fcf8d2ac-a150-48b4-bc4e-551946881876)
> 你在浏览器能否打开这张图？看起来是图片加载失败。

不能，我试过，点开链接显示404，学长，我截的浏览器报错的那张图上有跟这个有关的吗

**Comment by yangjian102621** [comment]
那说明你的图片没有上传成功，如果你用的是反代，那可能是你的反代服务器故障了。

**Comment by longtiequan** [comment]
> 那说明你的图片没有上传成功，如果你用的是反代，那可能是你的反代服务器故障了。

学长，你那个画图接口的配置在哪里啊

**Comment by yangjian102621** [comment]
> > 那说明你的图片没有上传成功，如果你用的是反代，那可能是你的反代服务器故障了。
> 
> 学长，你那个画图接口的配置在哪里啊

在管理后台，添加 API KEY 的时候，用途选择绘图就好了。
![image](https://github.com/yangjian102621/geekai/assets/4746061/137259aa-dc30-4565-ba14-3e0af86752b6)
