### ISSUE TITLE
 Docker Compose 和 Docker API 之间的兼容性问题

### ISSUE THREAD

**Issue by luojin520520** [yangjian102621/geekai#107]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

Ubuntu系统为大佬推荐的系统。
python环境安装完整，Docker环境完整。阿里云服务器（东京）。但无法安装。
通过chatgpt4检测错误信息后，是这样的结果，但是更新docker依然没有反应。—

_

> 从您提供的信息来看，您在安装 ChatGPT Plus v3.2.0 时遇到了一个问题，特别是在使用 Docker Compose 的过程中。出现的错误提示是 TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'，这通常指向了 Docker Compose 和 Docker API 之间的兼容性问题。
> 
> 要解决这个问题，您可以尝试以下步骤：
> 
> 更新 Docker Compose：
> 
> 您目前使用的 Docker Compose 版本似乎是 1.29.2，这可能与您的 Docker 版本不兼容。
> 您可以尝试更新 Docker Compose 到最新版本。您可以访问 Docker Compose 的 GitHub 仓库 查找最新版本，并按照那里的指示进行更新。
> 检查 Docker 版本：
> 
> 确保您的 Docker 版本是最新的。您可以通过运行 docker --version 来检查当前安装的版本。
> 如果需要，您可以通过 Docker 官方文档了解如何更新 Docker 到最新版本。
> 重新运行安装脚本：
> 
> 在更新了 Docker Compose 后，重新尝试运行 ChatGPT Plus 的安装脚本。
> 考虑依赖问题：
> 
> 检查是否所有必要的依赖包都已经安装且为最新版本。这包括 Python 以及其它相关的库。
> 查看错误日志：
> 
> 详细查看错误日志可能会提供更多关于问题的线索。特别是，关注与 Docker Compose 相关的错误信息。
> 寻求帮助：
> 
> 如果问题依然存在，您可以考虑在 ChatGPT Plus 的 GitHub 仓库中提一个 issue，或者在 Docker 相关的社区论坛寻求帮助。
> 请在执行任何更新或更改时保持谨慎，并确保您了解每个步骤的作用。在对系统进行重大更改之前，建议备份重要数据。

_

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
我的错误信息如下————————
You are installing chatgpt-plus-v3.2.0 source code：https://github.com/yangjian102621/chatgpt-plus
Hit:1 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:2 http://mirrors.cloud.aliyuncs.com/ubuntu jammy InRelease
Hit:3 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-updates InRelease
Hit:4 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-backports InRelease
Hit:5 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.15).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 195 not upgraded.
File '/etc/apt/keyrings/docker.gpg' exists. Overwrite? (y/N) y
Hit:1 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:2 http://mirrors.cloud.aliyuncs.com/ubuntu jammy InRelease
Hit:3 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-updates InRelease
Hit:4 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-backports InRelease
Hit:5 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-security InRelease
Reading package lists... Done                                
Try to installing docker ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
containerd.io is already the newest version (1.6.26-1).
docker-buildx-plugin is already the newest version (0.11.2-1~ubuntu.22.04~jammy).
docker-ce-cli is already the newest version (5:24.0.7-1~ubuntu.22.04~jammy).
docker-ce is already the newest version (5:24.0.7-1~ubuntu.22.04~jammy).
docker-compose-plugin is already the newest version (2.21.0-1~ubuntu.22.04~jammy).
The following additional packages will be installed:
  python3-certifi python3-docker python3-dockerpty python3-docopt python3-dotenv python3-jsonschema python3-pyrsistent
  python3-requests python3-texttable python3-urllib3 python3-websocket
Suggested packages:
  python-jsonschema-doc python3-socks python-requests-doc
Recommended packages:
  docker.io
The following NEW packages will be installed:
  docker-compose python3-certifi python3-docker python3-dockerpty python3-docopt python3-dotenv python3-jsonschema
  python3-pyrsistent python3-requests python3-texttable python3-urllib3 python3-websocket
0 upgraded, 12 newly installed, 0 to remove and 195 not upgraded.
Need to get 686 kB of archives.
After this operation, 3,090 kB of additional disk space will be used.
Get:1 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/main amd64 python3-certifi all 2020.6.20-1 [150 kB]
Get:2 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-updates/main amd64 python3-urllib3 all 1.26.5-1~exp1ubuntu0.1 [98.2 kB]
Get:3 http://mirrors.cloud.aliyuncs.com/ubuntu jammy-updates/main amd64 python3-requests all 2.25.1+dfsg-2ubuntu0.1 [48.8 kB]
Get:4 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 python3-websocket all 1.2.3-1 [34.7 kB]
Get:5 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 python3-docker all 5.0.3-1 [89.3 kB]
Get:6 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 python3-dockerpty all 0.4.1-2 [11.1 kB]
Get:7 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 python3-docopt all 0.6.2-4 [26.9 kB]
Get:8 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 python3-dotenv all 0.19.2-1 [20.5 kB]
Get:9 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/main amd64 python3-pyrsistent amd64 0.18.1-1build1 [55.5 kB]
Get:10 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/main amd64 python3-jsonschema all 3.2.0-0ubuntu2 [43.1 kB]
Get:11 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 python3-texttable all 1.6.4-1 [11.4 kB]
Get:12 http://mirrors.cloud.aliyuncs.com/ubuntu jammy/universe amd64 docker-compose all 1.29.2-1 [95.8 kB]
Fetched 686 kB in 2s (450 kB/s)       
Selecting previously unselected package python3-certifi.
(Reading database ... 80603 files and directories currently installed.)
Preparing to unpack .../00-python3-certifi_2020.6.20-1_all.deb ...
Unpacking python3-certifi (2020.6.20-1) ...
Selecting previously unselected package python3-urllib3.
Preparing to unpack .../01-python3-urllib3_1.26.5-1~exp1ubuntu0.1_all.deb ...
Unpacking python3-urllib3 (1.26.5-1~exp1ubuntu0.1) ...
Selecting previously unselected package python3-requests.
Preparing to unpack .../02-python3-requests_2.25.1+dfsg-2ubuntu0.1_all.deb ...
Unpacking python3-requests (2.25.1+dfsg-2ubuntu0.1) ...
Selecting previously unselected package python3-websocket.
Preparing to unpack .../03-python3-websocket_1.2.3-1_all.deb ...
Unpacking python3-websocket (1.2.3-1) ...
Selecting previously unselected package python3-docker.
Preparing to unpack .../04-python3-docker_5.0.3-1_all.deb ...
Unpacking python3-docker (5.0.3-1) ...
Selecting previously unselected package python3-dockerpty.
Preparing to unpack .../05-python3-dockerpty_0.4.1-2_all.deb ...
Unpacking python3-dockerpty (0.4.1-2) ...
Selecting previously unselected package python3-docopt.
Preparing to unpack .../06-python3-docopt_0.6.2-4_all.deb ...
Unpacking python3-docopt (0.6.2-4) ...
Selecting previously unselected package python3-dotenv.
Preparing to unpack .../07-python3-dotenv_0.19.2-1_all.deb ...
Unpacking python3-dotenv (0.19.2-1) ...
Selecting previously unselected package python3-pyrsistent:amd64.
Preparing to unpack .../08-python3-pyrsistent_0.18.1-1build1_amd64.deb ...
Unpacking python3-pyrsistent:amd64 (0.18.1-1build1) ...
Selecting previously unselected package python3-jsonschema.
Preparing to unpack .../09-python3-jsonschema_3.2.0-0ubuntu2_all.deb ...
Unpacking python3-jsonschema (3.2.0-0ubuntu2) ...
Selecting previously unselected package python3-texttable.
Preparing to unpack .../10-python3-texttable_1.6.4-1_all.deb ...
Unpacking python3-texttable (1.6.4-1) ...
Selecting previously unselected package docker-compose.
Preparing to unpack .../11-docker-compose_1.29.2-1_all.deb ...
Unpacking docker-compose (1.29.2-1) ...
Setting up python3-dotenv (0.19.2-1) ...
Setting up python3-texttable (1.6.4-1) ...
Setting up python3-docopt (0.6.2-4) ...
Setting up python3-certifi (2020.6.20-1) ...
Setting up python3-urllib3 (1.26.5-1~exp1ubuntu0.1) ...
Setting up python3-pyrsistent:amd64 (0.18.1-1build1) ...
Setting up python3-websocket (1.2.3-1) ...
Setting up python3-dockerpty (0.4.1-2) ...
Setting up python3-jsonschema (3.2.0-0ubuntu2) ...
Setting up python3-requests (2.25.1+dfsg-2ubuntu0.1) ...
Setting up python3-docker (5.0.3-1) ...
Setting up docker-compose (1.29.2-1) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...                                                                                                               
Scanning linux images...                                                                                                            

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
Try to download installation package...
--2024-01-10 21:51:24--  https://img.r9it.com/tmp/install-v3.2.4-7b5ff48154.tar.gz
Resolving img.r9it.com (img.r9it.com)... 124.236.103.55, 182.131.21.252, 183.60.150.17, ...
Connecting to img.r9it.com (img.r9it.com)|124.236.103.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16975 (17K) [application/x-gzip]
Saving to: ‘install.tar.gz’

install.tar.gz                   100%[==========================================================>]  16.58K  --.-KB/s    in 0s      

2024-01-10 21:51:24 (205 MB/s) - ‘install.tar.gz’ saved [16975/16975]

tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.metadata:kMDItemWhereFroms'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'

**Comment by yangjian102621** [comment]
兼容性应该是你的docker 版本不对，你安装最新版的 docker 试下，我们一键部署脚本也是安装最新版的 docker，运行一切正常。
