### ISSUE TITLE
MJ有时候会出现不现实生成图片进度

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#108]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

<img width="1015" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/ebd44f6f-116e-4263-bf71-0783e0899196">
<img width="1014" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/58176e11-f99e-48dd-a09a-586a7cca06dc">

经常遇到，点击生成图片后，不显示进度条，也不显示图片，如果切换到其他tab，比如展示墙是可以看到图的，再返回来可以在『创作记录』看到刚才的进度和结果

### 重现步骤 🕹

1. 点击MJ生成图片
2. 看不到进度
3. 切换到其他的tab，比如展示墙
4. 切换回MJ来才能看到生成结果

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
应该是网络连接不稳定。Websocket 断线了，导致后台不能及时把数据推送回前端。不过一般断线后自动重连的，你这没有重连应该是网络不稳导致重连失败。

**Comment by SericWong** [comment]
<img width="995" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/ead7d775-dc24-4967-8a91-83bf573e05e5">

不是网络问题，不出进度条这个可以稳定复现，直接拉的3.2.4版本没修改
另外还一个问题是，对于历史生成的图片（比如昨天的图）再点U、V操作，都会没反应，出现排队，但看mjbot没有收到信息，看log也后端也没收到信息

**Comment by yangjian102621** [comment]
如果你只有一个 MJ 服务的话，出现排队是正常的。想要并发执行需要多配置几个 MJ 机器人。否则即使我这边帮你把任务推送过去了 discord 那边也会给你排队的。不会立即执行。

**Comment by SericWong** [comment]
不是排队问题，我配置了多个mj机器人，我在discord里看是没有收到信息的
复现方式是对于之前生成的图，点u、v都不会发送给discord
