### ISSUE TITLE
不能解析数学公式

### ISSUE THREAD

**Issue by hjxwz123** [yangjian102621/geekai#114]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

不能正确解析显示latex和其它类型的数学公式

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到，感谢反馈，将在 v3.2.7 版本加入次功能。
