### ISSUE TITLE
移动端，首次进入需要手动缩放一下

### ISSUE THREAD

**Issue by HaoKaiFang** [yangjian102621/geekai#115]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

移动端，首次进入需要手动缩放一下， 建议优化index.html中 mate标签 user-scalable=no

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by HaoKaiFang** [comment]
建议优化 index.html <mate> 建议改为  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

**Comment by yangjian102621** [comment]
收到，感谢反馈。
