### ISSUE TITLE
DALL-E3绘图失败

### ISSUE THREAD

**Issue by bjzhaoxy** [yangjian102621/geekai#118]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Windows

### Bug 描述 📝

会话都没什么问题，使用DALL-E3绘图失败，后台也没报什么错，错误如图：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/14307569/dfa585ec-0793-4d34-9939-012f7d509348)
浏览器可以打开https://oaidalleapiprodscus.blob.core.windows.net/private/org-eaXaqVV2v764KbMSvOunh0mR/user-KjwrNFy2CVQ6rRDVFI0JTQk5/img-CWTxHTVZlxtuDHMGYNsjb0L3.png?st=2024-01-25T07%3A20%3A30Z&se=2024-01-25T09%3A20%3A30Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-01-24T22%3A02%3A13Z&ske=2024-01-25T22%3A02%3A13Z&sks=b&skv=2021-08-06&sig=alEGpem9tqLrVVTcA6ws8kSY7t1BNXh7tMSoJmiJQas%3D这个地址的图片，图片就是我要画的东西

### 重现步骤 🕹

画什么都不行

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
Listen = "0.0.0.0:5678"
ProxyURL = "http://127.0.0.1:7890" # 如 http://127.0.0.1:7777
MysqlDns = "root:123456@tcp(127.0.0.1:3306)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

**Comment by bjzhaoxy** [comment]
http://127.0.0.1:7890/是我本地的clash代理地址

**Comment by yangjian102621** [comment]
确保用你的代理能够正常访问这张图片。用 curl 带上你的代理地址看能否把图片下载下来，根据报错提示明显是下载图片失败了。
