### ISSUE TITLE
管理后台删除用户问题

### ISSUE THREAD

**Issue by 602753090** [yangjian102621/geekai#124]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

管理员后台删除用户以后，使用被删除的账号重新注册登录，发送对话收到提示：非法用户，请联系管理员

**Comment by yangjian102621** [comment]
已测试，没法重新您说的问题。

**Comment by Everaine0** [comment]
后台重新设一下密码就解决了
