### ISSUE TITLE
3.2.4及3.2.4.1版本启动api报错

### ISSUE THREAD

**Issue by wshze** [yangjian102621/geekai#126]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

 [Fx] PROVIDE	*handler.TestHandler <= chatplus/handler.NewTestHandler()
 [Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()
 [Fx] PROVIDE	fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
 [Fx] PROVIDE	fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
 [Fx] INVOKE		main.main.func3()
 [Fx] INVOKE		main.main.func7()
 2024-01-29T14:24:38.967+0800	ERROR	api/main.go:64	Panic Error:runtime error: invalid memory address or nil pointer dereference

### 重现步骤 🕹

全新的环境和下载的新包，改完配置后去go run main.go启动报错误
2024-01-29T14:24:38.967+0800	ERROR	api/main.go:64	Panic Error:runtime error: invalid memory address or nil pointer dereference
试过用容器build后再启动也一样报这个错误，但是3.2.3和3.2.2就没问题。（我用的centos7.9，windows下没问题，很奇怪）

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by MaZhaolin** [comment]
我安装最新的版本也遇到了同样的问题
<img width="588" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/13713662/dbdacab5-9ff9-4828-981b-34a52ef0ab7c">
