### ISSUE TITLE
获取当前用户邀请码接口生成邀请码有bug

### ISSUE THREAD

**Issue by huhansan01** [yangjian102621/geekai#131]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝
![Snipaste_2024-02-01_16-14-53](https://github.com/yangjian102621/chatgpt-plus/assets/125582913/5e555e1b-46ad-458b-9fc5-366f753ff4e8)

生成邀请码逻辑应该放在for循环里面,如果生成的邀请码已经存在了会死循环。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到，感谢反馈，将在下个版本修复此 Bug
