### ISSUE TITLE
新增GPTS ID数据库字段超长

### ISSUE THREAD

**Issue by lyzcodebool** [yangjian102621/geekai#137]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

<img width="612" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/28481065/1f0681f1-c073-4ca6-bed7-bd1849166d8d">
如果GPTSiD比较长 数据插入会失败，错误信息如下，希望优化
[35;1mError 1406 (22001): Data too long for column 'value' at row 1
[0m[33m[77.892ms] [34;1m[rows:0][0m INSERT INTO `chatgpt_chat_models` (`created_at`,`updated_at`,`platform`,`name`,`value`,`sort_num`,`enabled`,`weight`,`open`) VALUES ('2024-02-04 18:53:43.56','2024-02-04 18:53:43.56','OpenAI','g-WZjelkFDn-academic-translator-to-english','gpt-4-gizmo-g-WZjelkFDn-academic-translator-to-english',0,true,1,true)

顺便问下  需要配合文件使用的GPTS本系统也支持吗，希望大佬解答，已Start

**Comment by yangjian102621** [comment]
后面那一串貌似不用填吧，GPTS 应该只要填gpt-4-gizmo-g-WZjelkFDn 这一个就行了
