### ISSUE TITLE
按照说明文档配置mj-plus之后无法绘图，显示任务推送失败：添加任务失败：Error 1054 (42S22): Unknown column 'publish' in 'field list'

### ISSUE THREAD

**Issue by huxiaotao0620** [yangjian102621/geekai#143]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

按照说明文档配置mj plus之后无法绘图
![9HC5U}DYPWKWA86$N94XXIB](https://github.com/yangjian102621/chatgpt-plus/assets/73591035/c9cd9fb3-2b14-4aad-9932-b1cb323f19a3)

### 你的应用配置信息

Listen = "0.0.0.0:5678"
ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(chatgpt-plus-mysql:3306)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
ImgCdnURL = ""
WeChatBot = false

[Session]
  SecretKey = "数据脱敏" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Manager]
  Username = "数据脱敏"
  Password = "数据脱敏" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "chatgpt-plus-redis"
  Port = 6379
  Password = "12345678"
  DB = 0

[ApiConfig] # 微博热搜，今日头条等函数服务 API 配置，此为第三方插件服务，如需使用请联系作者开通
  ApiURL = ""
  AppId = ""
  Token = ""

[SmsConfig] # 阿里云短信服务配置
  AccessKey = ""
  AccessSecret = ""
  Product = "Dysmsapi"
  Domain = "dysmsapi.aliyuncs.com"
  Sign = ""
  CodeTempId = ""

[Sms] # Sms 配置，用于发送短信
   Active = "Ali" # 当前启用的短信服务，默认使用阿里云
   [Sms.SmsBao]
      Username = ""
      Password = ""
      Domain = "api.smsbao.com"
      Sign = "【极客学长】"
      CodeTemplate = "您的验证码是{code}。5分钟有效，若非本人操作，请忽略本短信。"
   [Sms.Ali]
      AccessKey = ""
      AccessSecret = ""
      Product = "Dysmsapi"
      Domain = "dysmsapi.aliyuncs.com"
      Sign = ""
      CodeTempId = ""

[OSS] # OSS 配置，用于存储 MJ 绘画图片
   Active = "local" # 默认使用本地文件存储引擎
   [OSS.Local]
     BasePath = "./static/upload" # 本地文件上传根路径
     BaseURL = "http://localhost:5678/static/upload" # 本地上传文件根 URL 如果是线上，则直接设置为 /static/upload 即可
   [OSS.Minio]
     Endpoint = "" # 如 172.22.11.200:9000
     AccessKey = "" # 自己去 Minio 控制台去创建一个 Access Key
     AccessSecret = ""
     Bucket = "chatgpt-plus" # 替换为你自己创建的 Bucket，注意要给 Bucket 设置公开的读权限，否则会出现图片无法显示。
     UseSSL = false
     Domain = "" # 地址必须是能够通过公网访问的，否则会出现图片无法显示。
   [OSS.QiNiu] # 七牛云 OSS 配置
       Zone = "z2" # 区域，z0：华东，z1: 华北，na0：北美，as0：新加坡
       AccessKey = ""
       AccessSecret = ""
       Bucket = ""
       Domain = "" # OSS Bucket 所绑定的域名，如 https://img.r9it.com

[[MjConfigs]]
  Enabled = false
  UserToken = ""
  BotToken = ""
  GuildId = ""
  ChanelId = ""
  UseCDN = false #是否使用反向代理访问，设置为true下面的设置才会生效
  DiscordAPI = "https://mj.r9it.com:8001" # discord API 反代地址
  DiscordCDN = "https://mj.r9it.com:8002" # mj 图片反代地址
  DiscordGateway = "wss://mj.r9it.com:8003" # discord 机器人反代地址

[[MjPlusConfigs]]
  Enabled = true
  ApiURL = "https://api.chatgpt-plus.net" # 目前暂时不支持更改
  ApiKey = "数据脱敏"
  NotifyURL = "http://数据脱敏/api/mj/notify" # 这里需要改成你的域名

[[SdConfigs]]
  Enabled = false
  ApiURL = ""
  ApiKey = ""
  Txt2ImgJsonPath = "res/sd/text2img.json"

**Comment by yangjian102621** [comment]
数据库的版本和代码不一致，缺少字段。
