### ISSUE TITLE
后台添加了OpenAI得key，前台对话没反应

### ISSUE THREAD

**Issue by yan-sheng-li** [yangjian102621/geekai#156]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

我是部署到服务器上，docker-compose方式启动，后台新增了openAI的key，前台对话没有想响应，不知道是哪步出了问题

### 重现步骤 🕹

- 添加key

![图片](https://github.com/yangjian102621/chatgpt-plus/assets/68138841/4cc1381f-aaeb-44a1-a540-fc39d9d8c252)

- 提示连接对话成功

![图片](https://github.com/yangjian102621/chatgpt-plus/assets/68138841/1b78597a-f8b2-4960-b0b9-c1095cb3888c)

- 对话中一直提示开小差了
![图片](https://github.com/yangjian102621/chatgpt-plus/assets/68138841/8c2d8e08-fd61-4961-bf45-979b1eeab329)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
version: '3'
services:
  # mysql
  chatgpt-plus-mysql:
    image: mysql:8.0.33
    container_name: chatgpt-plus-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3307:3306"
    volumes :
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d/
  
  # redis 
  chatgpt-plus-redis:
    image: redis:6.0.16
    restart: always 
    container_name: chatgpt-plus-redis
    command: redis-server --requirepass 12345678
    volumes :
      - ./redis/data:/data
    ports:
      - "6380:6379"

  # 后端 API 程序
  chatgpt-plus-api:
    image: registry.cn-shenzhen.aliyuncs.com/geekmaster/chatgpt-plus-api:v3.1.8.1
    container_name: chatgpt-plus-api
    restart: always
    depends_on:
      - chatgpt-plus-mysql
      - chatgpt-plus-redis
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
      - CONFIG_FILE=config.toml
    ports:
      - "5678:5678"
      - "9999:9999"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./conf/config.toml:/var/www/app/config.toml
      - ./logs:/var/www/app/logs
      - ./static:/var/www/app/static

  # 前端应用
  chatgpt-plus-web:
    image: registry.cn-shenzhen.aliyuncs.com/geekmaster/chatgpt-plus-web:v3.1.8.1
    container_name: chatgpt-plus-web
    restart: always
    depends_on:
      - chatgpt-plus-api
    ports:
      - "8080:8080"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl

**Comment by mrchenzifan** [comment]
你填的是从[bemore](https://gpt.bemore.lol/)还或是官网买的？API URL要对应上啊！
![1709620529142](https://github.com/yangjian102621/chatgpt-plus/assets/16876976/34b7dd83-8d14-4b33-bea7-ed17459761d8)

**Comment by yangjian102621** [comment]
看下后端的详细报错日志在 logs/app/app.log
