### ISSUE TITLE
支持会员和试用用户分开计费逻辑

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#163]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

现在的计费逻辑，没办法实现 在试用阶段用户可以体验N次gpt3.5，在充值会员后免费使用3.5或者额外开放gpt4、dalle模型，这个功能很实用，如果有了，就可以支持非常多的组合规则：
1、用户体验阶段可以使用gpt3.5 20次以及gpt4 2次（并的关系，现在只能或）
2、充值会员后，可以配置会员使用模型，这样就可以用另一个gpt3.5（计费为0），实现会员的gpt3.5无限使用，并且保证了非会员只能体验N次 gpt3.5
3、可以实现会员使用额外模型，比如会员额外体验gpt4-all，claude3模型

以上只需要支持自动的会员额外配置模型，就可以实现上面三种需求变化，希望学长可以支持下，非常刚需的功能。

**Comment by yangjian102621** [comment]
我们的模型不只是有 GPT-35 和 GPT-4, 还有讯飞 3.5， 文心 4.0 等。所以不会为每个模型设置体验的次数，这样用户的调用规则会极为复杂，目前这种通过模型权重（倍率）来控制是比较好的方式，你设置设置免费用户体验从次数为100次，如果哟个3.5 就是100次，如果4.0 的倍率为10，那么如果他使用4.0 就只能使用 10 次。目前可以为每个会员设置他能使用的模型。
个性化的规则，建议走二次开发。
