### ISSUE TITLE
3.2.7版本中的配置修改导致api服务启动会失败

### ISSUE THREAD

**Issue by CharryMoon** [yangjian102621/geekai#168]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/1135968/c488becc-d234-4150-be81-0149093f7fb4)
如上图。这个部分的参数修改后会导致api服务启动失败。

### 重现步骤 🕹

使用3.2.7镜像部署，无法直接成功，查看配置后发现如图上的修改点。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
默认配置

**Comment by w5185552** [comment]
是的容器内部的地址 应该使用左边的

**Comment by yangjian102621** [comment]
@CharryMoon 启动失败，具体报什么错呢？

**Comment by CharryMoon** [comment]
> @CharryMoon 启动失败，具体报什么错呢？
启动会报错连接对应的服务失败。
3.2.6的配置是正常的，使用container name来访问。
我看已经有人提了一个pr来修改这个参数
