### ISSUE TITLE
人机验证的图形验证能否自己关闭

### ISSUE THREAD

**Issue by number9902** [yangjian102621/geekai#170]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

请问能否自己主动取消人机图形验证，使用自己的邮箱发送验证码注册账号的服务

**Comment by yangjian102621** [comment]
你关闭手机注册和邮箱注册，图形验证码服务自然就关闭了。
