### ISSUE TITLE
azure的函数调用不生效

### ISSUE THREAD

**Issue by Dreamshe-92** [yangjian102621/geekai#174]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

采用的是azure的gpt-35-turbo和gpt4   2024-02-15-preview，全部服务都是启动的
![image](https://github.com/yangjian102621/chatgpt-plus/assets/29124038/2e3dc33a-9cb8-4600-a0f1-94e827031cc3)

### 重现步骤 🕹

![image](https://github.com/yangjian102621/chatgpt-plus/assets/29124038/2e3dc33a-9cb8-4600-a0f1-94e827031cc3)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
正常deplay配置docker部署

**Comment by yangjian102621** [comment]
Azure 模型本身就不支持函数调用。你可以自己试下手动调用 API，看是否支持。
