### ISSUE TITLE
虎皮椒更新了pc端支付扫码接口

### ISSUE THREAD

**Issue by kaine380** [yangjian102621/geekai#179]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

使用接口返回的二维码可以直接扫码，不必跳转到网页
https://www.xunhupay.com/324.html

**Comment by kaine380** [comment]
//hupiPay 单独处理，使用微信二维码
	if data.PayWay == "hupi" { // 虎皮椒支付
		params := payment.HuPiPayReq{
			Version:      "1.1",
			TradeOrderId: orderNo,
			TotalFee:     fmt.Sprintf("%f", order.Amount),
			Title:        order.Subject,
			NotifyURL:    h.App.Config.HuPiPayConfig.NotifyURL,
			WapName:      "ChatAI",
		}
		r, err := h.huPiPayService.Pay(params)
		if err != nil {
			resp.ERROR(c, "error with generating payment qrcode: ")
			return
		} else {
			resp.SUCCESS(c, gin.H{"order_no": order.OrderNo, "image": r.UrlQrcode})
			fmt.Println(r.UrlQrcode)
			return
		}
	}
	写在payjs单独处理下面

**Comment by yangjian102621** [comment]
这个是故意设计成这样的。统一的交互体验，而且扫码需要有反馈扫码成功，官方提供的二维码没有这功能。

**Comment by kaine380** [comment]
> 这个是故意设计成这样的。统一的交互体验，而且扫码需要有反馈扫码成功，官方提供的二维码没有这功能。

除了没有扫描成功的提示，其他还行，可以提示支付成功，我这边的运营商屏蔽了虎皮椒的域名，开wifi扫不了码，这样直接扫支付码成功率高一点

**Comment by yangjian102621** [comment]
> > 这个是故意设计成这样的。统一的交互体验，而且扫码需要有反馈扫码成功，官方提供的二维码没有这功能。
> 
> 除了没有扫描成功的提示，其他还行，可以提示支付成功，我这边的运营商屏蔽了虎皮椒的域名，开wifi扫不了码，这样直接扫支付码成功率高一点

你直接扫码也是需要打开虎皮椒的域名的，应该没法避免的。
