### ISSUE TITLE
4.0版本 MJ绘图进度出错

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#187]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

![b0cc91e692f1a0938ae34359ff5603e6](https://github.com/yangjian102621/chatgpt-plus/assets/5850668/253c61ec-00d1-4361-bfba-f1939f25d240)

MJ画图，用的是api接口方式，图像进度显示一半时，下面就显示下载，最终也不会成功，需要刷新页面才行

### 重现步骤 🕹

如上

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
新版已修复这个问题
