### ISSUE TITLE
4.0.4 不登录提示錯誤

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#190]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

<img width="514" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/d5f6479b-99d4-43c1-918b-52c7fcdc9f22">

没有登录时，访问mj页面，什么都不点 会弹这个窗口

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
新版已修复。感谢反馈
