### ISSUE TITLE
未登录下访问mj页面，出错

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#191]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

<img width="386" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/07853762-8478-45ee-803f-7bd67244fba9">

未登录下，访问mj出错
试着改了下
const fetchFinishJobs = (page) => {
  if (isLogin.value == false){
      return
  }
这样验证下是否登录，解决了，不知道对不对

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
可以这样处理，新版本会修复这个问题。
