### ISSUE TITLE
切换模型后页面不断自动刷新

### ISSUE THREAD

**Issue by yinmao** [yangjian102621/geekai#194]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

页面上切换模型，如从GPT-3.5切换到通义千问，切换后页面会多次自动刷新，后端多次打印：
`2024-05-03T14:07:46.038+0800	INFO	chatimpl/chat_handler.go:130	New websocket connected, IP: 107.182.188.23, Username: 18575670125`
期间无法正常操作，需自动刷新完成后才能操作

### 重现步骤 🕹

切换模型

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by SericWong** [comment]
我也遇到这个问题+1

**Comment by yangjian102621** [comment]
感谢反馈，目前切换模型会重新连接，但是页面应该不会刷新，你不妨试下演示站 https://ai.r9it.com/chat 看看有没有这个问题。
