### ISSUE TITLE
使用中转接口报不在白名单中

### ISSUE THREAD

**Issue by thisisdun998** [yangjian102621/geekai#199]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

使用中转接口报不在白名单中

**Comment by Anionex** [comment]
同样的问题

**Comment by magicwen666** [comment]
同样的问题

**Comment by KyanZhu** [comment]
> ![image](https://private-user-images.githubusercontent.com/4746061/334609589-c1d6c2f1-a314-4a5d-bfac-01d42ef6df65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzI0MzIsIm5iZiI6MTcxNzEzMjEzMiwicGF0aCI6Ii80NzQ2MDYxLzMzNDYwOTU4OS1jMWQ2YzJmMS1hMzE0LTRhNWQtYmZhYy0wMWQ0MmVmNmRmNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDUwODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNjODk3ZDA2OTMxNzFlOTI4YzM0MTcwMmY5OGNlODFiNmYyNjVmZmJiNGVkMmVkNTE1NzVmYmFjNzlhODNjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r5GReeVykT4NW7TwziQl3bUPwNIzoZNy-oCYL8QHsp4)
> 
> 配置一下 API 地址，这个是获取白名单列表的 API。

可以在说的详细一点嘛 谢谢

**Comment by yangjian102621** [comment]
编辑 conf/config.toml 配置文档，找到 ApiConfig 配置段，把 ApiURL 这个配置配上，http://service.r9it.com:9001

**Comment by tomlongcool** [comment]
配置文件在哪里请问，我是用的宝塔和docker一键部署的

**Comment by tomlongcool** [comment]
> 同样的问题

请问解决了吗 我找不到这个配置文件

**Comment by tomlongcool** [comment]
> 编辑 conf/config.toml 配置文档，找到 ApiConfig 配置段，把 ApiURL 这个配置配上，http://service.r9it.com:9001

您好，作者大大，我用宝塔和docker一键部署的找不到这个文件，请问怎么修改呢？

**Comment by yangjian102621** [comment]
就在你的部署目录下面，有个 conf 文件夹。
