### ISSUE TITLE
mj 删除图像后 不显示，需要刷新才能成功

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#202]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

midjouney的图像生成后，想删除，删除点击没有反应，必须要刷新页面才行

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
感谢反馈，在新版本中已经修复。
