### ISSUE TITLE
页面向上滑动，底部出现空白页

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/geekai#203]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

<img width="1350" alt="image" src="https://github.com/yangjian102621/geekai/assets/5850668/1abd3774-98d6-435e-841c-4f898eca8a67">
<img width="1317" alt="image" src="https://github.com/yangjian102621/geekai/assets/5850668/3828e26b-b958-4db2-9404-1307531a33ba">

<img width="1403" alt="image" src="https://github.com/yangjian102621/geekai/assets/5850668/fee5b835-687f-4c3f-8653-670c9fe0c632">

在windows的chrome和mac的safiri浏览器都可以复现，页面向下拉 就会出现空白页，chat mj 个人中心这些页面都有

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by civitaic** [comment]
同样遇见这个问题，在登录账号为连接成功的情况下，登录成功就好了

**Comment by yangjian102621** [comment]
https://ai.r9it.com/chat 试下演示站，看看有没有这个问题，我测试没有发现。可能是社区版还没有更新。
