### ISSUE TITLE
geekai-api和geekai-mysql总是会启动成功后再自动暂停运行。

### ISSUE THREAD

**Issue by jetwong88** [yangjian102621/geekai#204]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

系统环境：Ubuntu22.04
中间件：宝塔面板
Docker安装运行正常。
GeekAI一键安装完成后，容器启动遇到问题，RT，geekai-api和geekai-mysql总是会启动成功后再自动暂停运行。
截图：
![1](https://github.com/yangjian102621/geekai/assets/18240301/dd538455-e59d-442b-9f75-29d07966207a)
![2](https://github.com/yangjian102621/geekai/assets/18240301/9c7df715-8a78-45bc-87a0-07216786ee88)
[748b472c957dff3fd1dc855e622aaa9d7f105a5f88283c0f51bbf8862c8bc777-json.log]

日志：
(https://github.com/yangjian102621/geekai/files/15430956/748b472c957dff3fd1dc855e622aaa9d7f105a5f88283c0f51bbf8862c8bc777-json.log)
[e6b526686f1eb6c402cfef91c799683d4d459a98f0bcad1bf80431fed34ea07e-json.log](https://github.com/yangjian102621/geekai/files/15430958/e6b526686f1eb6c402cfef91c799683d4d459a98f0bcad1bf80431fed34ea07e-json.log)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by jetwong88** [comment]
是不是内存太低了？MySQL8的支持不行，2GB的。

**Comment by yangjian102621** [comment]
中间会重启几次很正常，容器之间有依赖，不用管他，等会它们自动会调整好启动顺序启动成功的。
