### ISSUE TITLE
api 地址优化

### ISSUE THREAD

**Issue by civitaic** [yangjian102621/geekai#206]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

api地址后面带个v1/chat/completions，/v1/images/generations，让我整整花费一天时间，导出找问题，找原因，最好看了好几遍文档才看到这么个东西，才搞成功，和别家都不一样。部署教程写的很好，部署很顺利，但是api配置真麻烦，可以直接配域名吗？比如https://api.openai.com，https://api.chat-plus.net,

**Comment by civitaic** [comment]
而且API口令复制的页面也没有提示API地址，或者一键复制api地址的，感觉就很麻烦，买个API还要看一堆文档，对话和绘图的后缀还不一样...

**Comment by yangjian102621** [comment]
1. API复制口令是中转站提供的，我控制不了。
2. 后缀地址你选择平台的时候都会自动带出来的。你改下域名就好。
