### ISSUE TITLE
配置好openai的apiKey，使用代理地址后，模型中也关联了api-key，聊天时报错，当前 API 地址不在白名单列表当中。

### ISSUE THREAD

**Issue by 499909744** [yangjian102621/geekai#211]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

当前 API 地址 https://gateway.ai.cloudflare.com/v1/33114bxxxxxx/ai/openai/chat/completions 不在白名单列表当中。
添加API-KEY:
![image](https://github.com/yangjian102621/geekai/assets/16700590/22da4b47-a151-48f6-bd3d-0cb329fcbd8c)
模型关联API-KEY:
![image](https://github.com/yangjian102621/geekai/assets/16700590/67caf764-447d-4d27-8939-557075625388)
聊天时选择模型报错：
![image](https://github.com/yangjian102621/geekai/assets/16700590/461f6cc1-8d09-4afd-85b0-a075fde34227)

key和代理地址是正确的,curl接口调用正常：
![image](https://github.com/yangjian102621/geekai/assets/16700590/b7d233e7-4c5e-4bec-b9cd-b2a43744989a)

### 重现步骤 🕹

当前 API 地址 https://gateway.ai.cloudflare.com/v1/33114bxxxxxx/ai/openai/chat/completions 不在白名单列表当中。
添加API-KEY:
![image](https://github.com/yangjian102621/geekai/assets/16700590/22da4b47-a151-48f6-bd3d-0cb329fcbd8c)
模型关联API-KEY:
![image](https://github.com/yangjian102621/geekai/assets/16700590/67caf764-447d-4d27-8939-557075625388)
聊天时选择模型报错：
![image](https://github.com/yangjian102621/geekai/assets/16700590/461f6cc1-8d09-4afd-85b0-a075fde34227)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by Jiaxing-Zheng** [comment]
一键部署脚本，还是本地前后端分别部署的

**Comment by 499909744** [comment]
> 一键部署脚本，还是本地前后端分别部署的

一键部署的，不过我用代理这种方式可以用了，
![image](https://github.com/yangjian102621/geekai/assets/16700590/67944fa3-d044-45c5-a739-bd760410f880)

**Comment by yangjian102621** [comment]
一键部署脚本部署的是 plus 版本，社区请使用 docker-compose  快速部署的教程。https://ai.r9it.com/docs/install/quick.html
