### ISSUE TITLE
后台编辑语言模型值无法保存。

### ISSUE THREAD

**Issue by Zeitgeist0707** [yangjian102621/geekai#212]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Windows

### Bug 描述 📝

后台编辑语言模型值无法保存。

### 重现步骤 🕹

后台管理员界面→语言模型→编辑模型值→保存。
![图片](https://github.com/yangjian102621/geekai/assets/80456381/10c320e5-bdc9-44c9-871e-371e187a9f9e)
我是全新安装部署的4.0.6版本。其他后台配置一切都正常保存变更。只有语言模型这里更改后无法保存。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
你应该是数据库没有更新，缺少字段。
