### ISSUE TITLE
Stable-Diffusion在配置服务后Euler a是正常的，DPM++这些全部报404错误

### ISSUE THREAD

**Issue by z13260641200** [yangjian102621/geekai#216]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/geekai/assets/88540729/cfcf007d-97b1-48ee-b395-a6c5133a1144)

Stable-Diffusion在配置服务后Euler a是正常的，DPM++这些全部报404错误

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by z13260641200** [comment]
![image](https://github.com/yangjian102621/geekai/assets/88540729/7520af54-6d62-44d3-8636-326e7975d2a6)

**Comment by yangjian102621** [comment]
收到，感谢反馈，这个应该是不同的 SD 发行版 sample 的命名不一样，我是用秋叶的 2.8.4 这个版本测试的，其他版本我没有测试。比较便捷的修改方式就是把你的 SD 服务上的所有 sample 复制到 web/src/views/ImageSd.vue。

后面我会做一版重构，就是通过 API 动态读取你当前 SD 服务的 sample，并同步过来。

**Comment by z13260641200** [comment]
预计什么时候回修复这个问题呢？

**Comment by yangjian102621** [comment]
SD 后期可能不在支持了，功能很鸡肋。后面我打算直接对接 comfyUI 工作流。
