### ISSUE TITLE
MJ 绘图报错，提示原因：表单主体无效

### ISSUE THREAD

**Issue by z13260641200** [yangjian102621/geekai#220]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux

### Bug 描述 📝

MJ 绘图报错，提示原因：表单主体无效，采用的是MjProxy的方式接入
![image](https://github.com/yangjian102621/geekai/assets/88540729/cdb7ad0a-5ec2-43ce-bb87-9ce4b9ffdb30)

### 你的应用配置信息

![image](https://github.com/yangjian102621/geekai/assets/88540729/03c7e157-c87a-43d4-870f-df43ac288313)

**Comment by z13260641200** [comment]
版本是v4.0.5

**Comment by yangjian102621** [comment]
你有没有启动并配置 midjouney-proxy 容器呢？

**Comment by CodeLoken** [comment]
![Uploading image.png…]()
我也是这种情况

**Comment by CodeLoken** [comment]
我也是这种情况
![微信图片_20240712094112](https://github.com/user-attachments/assets/4d195070-3468-4b93-9484-2fb7fec5dbe5)
![微信图片_20240712094120](https://github.com/user-attachments/assets/86f40192-b282-44bf-b530-fca53aa03a1d)
