### ISSUE TITLE
WeChatBot 为 true后系统提示：获取系统配置失败：Request failed with status code 502

### ISSUE THREAD

**Issue by MIHU2077** [yangjian102621/geekai#221]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

WeChatBot 为 true后系统提示：获取系统配置失败：Request failed with status code 502

### 你的应用配置信息

Listen = "0.0.0.0:5678"
ProxyURL = ""
MysqlDns = "root:12345678@tcp(geekai-mysql:3306)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "/static"
WeChatBot = true

**Comment by yangjian102621** [comment]
502 是微信你微信启动之后没有扫码登录，导致后端服务没有情动成功。
