### ISSUE TITLE
文档打不开了

### ISSUE THREAD

**Issue by wpengsen** [yangjian102621/geekai#226]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

文档https://www.geekai.me/docs/打不开了

### 重现步骤 🕹

文档https://www.geekai.me/docs/打不开了

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
文档换了地址了，新的地址是 https://docs.geekai.me
