### ISSUE TITLE
项目文档里能不能加个教程把数据库之类的独立出来部署，本地已经有了mysql，docker里面再拉一个数据库，配置吃不消，用的宝塔面板

### ISSUE THREAD

**Issue by sommerzhao** [yangjian102621/geekai#228]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

**Comment by yangjian102621** [comment]
看下这个进阶部署教程：https://docs.geekai.me/install/advance.html
