### ISSUE TITLE
建议界面优化成响应式设计，这样可以适配移动端和pc端全平台。

### ISSUE THREAD

**Issue by 805934132** [yangjian102621/geekai#232]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

建议界面优化成响应式设计，这样可以适配移动端和pc端全平台。

### 示例 🌈

界面可以自动适配不同平台

### 动机 🔦

界面可以自动适配不同平台

**Comment by yangjian102621** [comment]
我是后端开发人人员，响应式开发我不会，主要是我对前端开发不感兴趣。如果你会的话，欢迎你贡献一份。
