### ISSUE TITLE
建议允许用户自己选择使用什么模型。建议支持微信和支付宝购买和充值的功能

### ISSUE THREAD

**Issue by 805934132** [yangjian102621/geekai#233]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

建议允许用户自己选择使用什么模型。建议支持微信和支付宝购买和充值的功能

### 示例 🌈

建议允许用户自己选择使用什么模型。建议支持微信和支付宝购买和充值的功能

### 动机 🔦

建议允许用户自己选择使用什么模型。建议支持微信和支付宝购买和充值的功能

**Comment by yangjian102621** [comment]
这些功能在 plus 版本中都已经实现了，后续会持续慢慢开源出来。
