### ISSUE TITLE
众筹核销选项

### ISSUE THREAD

**Issue by gianni2009** [yangjian102621/geekai#76]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

1、核销的时候能不能加上核销的是对话额度还是绘画额度。
2、或者添加一个对话和绘画互换的选项，在个人信息里面

**Comment by yangjian102621** [comment]
收到，已经加入开发列表。  #83

**Comment by yangjian102621** [comment]
该功能已实现，https://github.com/yangjian102621/chatgpt-plus/commit/de3eb8969cfa4b534422d7c50fcd602df24d6642#diff-468ed2f1f10f634a1d96297b399817061bf24c73522ec107f9b56c5d881691fd 将在 V3.2.4 上线。
