### ISSUE TITLE
从历史记录获取reply有并发风险

### ISSUE THREAD

**Issue by chj9** [yangjian102621/geekai#92]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

接口
/api/chat/tokens

### 示例 🌈

![image](https://github.com/yangjian102621/chatgpt-plus/assets/16426260/92702279-9762-4cbb-b266-efe5d47d5d95)
如图所示，该查询语句是获取回复的最后一条数据的
如果出现同个账号不同地方登录
出现同时使用的情况，可能会返回的token数据就会串了

### 解决方式 🔦
最好/api/chat/tokens接口的body入参新增chatId的入参

**Comment by yangjian102621** [comment]
感谢反馈，已修复，将在 v3.2.4 版本上线

![b99ead6c4a9d3c7e4f1948cc3490c31](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/50415256-800b-45bf-b57b-8dd61c8a31b9)
